name: Build and create a release when tag is pushed

# Only deploy when a new tag is pushed
on:
  push:
    tags:
      - "v*.*-alpha"
      - "v*.*.*"
  #     branches: [ master ]
  # pull_request:
  #     branches: [ master ]

# Allow this workflow to write back to the repository
permissions:
  contents: write

# Build binary and send to releases
jobs:
  build-release:
    runs-on: ubuntu-latest
    name: Build and release
    steps:

      - name: Install dependencies
        run: |
          sudo apt update && \
          sudo apt install -y git python3 && \
          sudo apt install -y cmake gcc-arm-none-eabi libnewlib-arm-none-eabi build-essential libusb-1.0-0-dev

      - name: Check out this repository
        uses: actions/checkout@v3

      - name: Print Working directory
        run: echo $HOME && pwd && ls -la

      - name: Install Pico SDk
        run: |
          cd $HOME && \
          git clone --depth 1 https://github.com/raspberrypi/pico-sdk.git --branch master && \
          cd pico-sdk/ && \
          git submodule update --init

      - name: Build the basic version
        run: |
          export PICO_SDK_PATH=$HOME/pico-sdk && \
          mkdir build && cd build && \
          cmake .. && make 

      - name: Build the overclocked versions
        run: |
          cd build && \
          cmake -DOVERCLOCKING=288 .. && make && \
          cmake -DOVERCLOCKING=300 .. && make && \
          cmake -DOVERCLOCKING=312 .. && make && \
          cmake -DOVERCLOCKING=333 .. && make && \
          cmake -DOVERCLOCKING=346 .. && make && \
          cmake -DOVERCLOCKING=366 .. && make && \
          cmake -DOVERCLOCKING=396 .. && make && \
          cmake -DOVERCLOCKING=412 .. && make && \
          cmake -DOVERCLOCKING=416 .. && make


      - name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bin/Release/**.uf2

          body_path: CHANGELOG.md
          
         
